### ISSUE TITLE
Post list should always include a title

### ISSUE THREAD

**Issue by thebaer** [writeas/writefreely-swiftui-multiplatform#103]
Right now, posts without an explicit post title show a blank space in the post list:

<img width="377" alt="Screen Shot 2020-10-21 at 11 58 33 AM" src="https://user-images.githubusercontent.com/1138779/96746211-f3204d00-1394-11eb-9ce1-87ddfb7f9fbc.png">

We should continue showing a post's title when it exists, but otherwise and fall back to showing a bit of **body** text. This is what happens on the web in WriteFreely -- we show up to 80 characters, stripping HTML and truncating at the first punctuation mark or newline character, otherwise adding an ellipsis at the 80-char limit. Full logic is here:

https://github.com/writeas/writefreely/blob/3493921837b18cc4239bd3d8252d71f97d5e1d5b/postrender.go#L175-L193

**Comment by AngeloStavrow** [comment]
Yes, I've been thinking about this too. Adding an `elidePostBody()` call in PostCellView that replicates the web experience seems like the right option here, since we've got the post there as an ObservedObject.
