### ISSUE TITLE
[iOS] Auto-focus on Title field upon loading empty editor

### ISSUE THREAD

**Issue by thebaer** [writeas/writefreely-swiftui-multiplatform#104]
When navigating to a brand new empty post in the editor, the Title field should automatically receive focus.

**Comment by AngeloStavrow** [comment]
Setting/resigning the first responder isn't available in SwiftUI, and just getting the keyboard to dismiss on publish required me to drop into UIKit. I _think_ we're going to have to use a custom TextField to get this behaviour.

I think this is an important enhancement.

**Comment by AngeloStavrow** [comment]
Per a conversation in Slack, let's also aim for this quality-of-life improvement:

> when typing in the Title field, [pressing] Return moves focus to the Body field
