### ISSUE TITLE
Set the a Collection for a Post based on selectedCollection w/ Drafts fallback

### ISSUE THREAD

**Issue by AngeloStavrow** [writeas/writefreely-swiftui-multiplatform#17]
New Posts are automatically set as "Draft" (i.e., no Collection) on creation, and there's no way to change this in the PostEditorView.

Similarly, existing Posts can't be moved from one Collection to another (or set to "Draft") in the PostEditorView.

**Comment by thebaer** [comment]
Perhaps we can break up the second part of this (moving Posts between Collections) into a separate issue? I'd consider _selecting a Collection to publish to_ crucial for the 1.0 beta, and _moving posts_ a "nice to have."

**Comment by AngeloStavrow** [comment]
That sounds like a plan.

Opened #39 for moving posts between collections. As for the UX of choosing a Collection for a new local Post, the new-post button has access to the `selectedCollection` state in the post list — I'd propose that, as default behaviour, the new-post button creates the new local Post in the current `selectedCollection` by default.

The question is, what happens in the "All Posts" lists, which is the default view? We could disable the button unless the user is viewing a specific collection, but that feels unexpected. We could default to Drafts, and wait until #39 is in place to allow the user to change it (#31 would indicate that the new local post is in Drafts, too).

**Comment by thebaer** [comment]
> I'd propose that, as default behaviour, the new-post button creates the new local Post in the current `selectedCollection` by default.

Sounds great :+1: 

> The question is, what happens in the "All Posts" lists, which is the default view?

I think defaulting to Drafts would make sense, as long as it's clear in the UI that this is what's happening. Then, assumedly, the user could go back and select a collection to publish to instead, if that's what they wanted.

**Comment by AngeloStavrow** [comment]
Perfect. 👍

I updated this issue's title to reflect the revised scope of the task.
