### ISSUE TITLE
Add a way to pull in new/updated content from the server

### ISSUE THREAD

**Issue by AngeloStavrow** [writeas/writefreely-swiftui-multiplatform#19]
Per #12 and #13, we can fetch user content (i.e., Collections then Posts) from the server to store it locally.

We should have a way to refresh the local content by fetching updated content from the server.

Some things to consider, as "proper" sync between local and remote content is outside of the scope for our 1.0:

1. Published Posts may be edited locally, but those changes have not yet been published.
2. Published Posts may be edited locally _and_ remotely.
3. Collections may have had their names changed.

@thebaer what are your thoughts on how to handle these conflicts (especially # 2)? Where do we consider the user's "ground truth" content to live, on a client or on the server? If on a client, how do we determine _which_ client?

**Comment by thebaer** [comment]
In the case of # 2, I think the ideal situation would be to use the same logic we have [in the web app](https://github.com/writeas/writefreely/pull/324):

* Upon editing and saving a local draft, save the `last-edited` time locally (along with the rest of the Post)
* Upon loading a local Post for editing, compare the remote `updated` time against the local `last-edited` time
  * If a local `last-edited` time doesn't exist (i.e. it was never edited locally), show the most up-to-date remote Post
  * If a local `last-edited` time is _after_ the remote Post `updated` time, show the local draft contents
  * If a local `last-edited` time is _before_ the remote Post `updated` time, show the local draft contents and notify the user -- they should have the choice to keep their local draft or overwrite it with the remote version

In the context of this app, where we save all Post data locally, I could imagine a few illustrative ways to implement this behind the scenes:

* Upon refresh, if conflict # 2, save the remote contents alongside the local draft contents. Then, if the user chooses to do so via the UI, overwrite local contents with remote contents.
* Upon refresh, only save the remote `updated` time for Posts with conflict # 2. If the user chooses to overwrite local contents, fetch the remote contents for that individual Post and replace locally.

Of course, I'll defer to you on the exact implementation. But the overall goal is to let people have per-Post control over which drafts they keep or toss in the case of local + remote conflicts.

**Comment by AngeloStavrow** [comment]
Okay, cool!

At this stage in development, nothing is persisted locally yet (that's coming in #16) — the app holds collections and posts in-memory for now, so if it gets terminated nothing beyond what's in the Keychain and UserDefaults (i.e., #8 and #10) stick around. Right now, that's okay, but the work being done on this issue should prepare for all use cases.

---

Here's how things work based on PR #32 for the scenarios I gave above.

**Scenario 1:** Published Posts may be edited locally, but those changes have not yet been published

- Current behaviour in #32: those changes are wiped out on reload (the user is warned of this and must confirm).

**Scenario 2:** Published Posts may be edited locally and remotely

- Current behaviour in #32: local changes are wiped out on reload (the user is warned of this and must confirm).

**Scenario 3:** Collections may have had their names changed remotely

- Current behaviour in #32: you can't change a Collection's name in the app; reloading from the server fetches the Collections first, then the Posts, so it can match things up properly.

Local-only posts (i.e., that have never been published to the server) persist on reload.

---

Here's what I understand as the end goal:

0. In the PostEditorView's `.onDisappear()` modifier, write the `updatedDate` time for the loaded local Post.
1. Local-only posts always persist on reload. This is the current behaviour.
2. Where a post exists both on the server _and_ in other clients<sup>1</sup>, _on reload_, compare remote and local `updatedDate` properties and:
    a) If the local Post has no `updatedDate` property, replace the local Post with the remote Post.
    b) If the local Post is newer, preserve the local Post and discard the remote Post.
    c) If the local Post is older, notify the user and allow them to overwrite local with remote (per-Post update).

This makes sense to me. The following work is therefore required:

- [ ] PostEditorView should write Post's updatedDate when the View is deallocated
- [ ] Preserve local copy of Post if it's newer than the remote Post
- [ ] Add hasNewerRemoteCopy flag to the Post type
- [ ] PostEditorView should indicate if remote Post is newer than local copy
- [ ] Implement per-Post update in PostEditorView if hasNewerRemoteCopy

Those last two feel like a new issue to me, in the interest of keeping PRs relatively small.

@thebaer — let me know if there's anything I missed!



<sup>1</sup> — I'd forgotten that the web client uses local storage.

**Comment by AngeloStavrow** [comment]
First pass at what it could look like in the editor if the remote copy is newer:

<img width="1434" alt="Post showing newer copy on server, prompting user to replace local copy." src="https://user-images.githubusercontent.com/387655/91565500-4c797c00-e910-11ea-8b74-4b704dccf4b0.png">
