### ISSUE TITLE
Login hangs when entering invalid instance URL

### ISSUE THREAD

**Issue by thebaer** [writeas/writefreely-swiftui-multiplatform#72]
## Description

Attempting to login to a non-WriteFreely instance causes the login screen to get stuck in the "Logging in..." state.

## Steps to reproduce

1. Go to Settings screen
1. Log out, if necessary
1. Enter username: `demo`, password: `demo`, and instance URL: `https://example.com` (not a valid WF instance)
1. Notice "Logging in..." message with no change

## Expected Result

An error message informing me that the app couldn't log in at that address.

### Design

Ideally we would be as specific as possible in the error message, telling the user exactly what went wrong, e.g. "This doesn't seem to be a compatible WriteFreely instance."

## Actual result

Login form is stuck in "Logging in..." state with no way to retry.

**Comment by thebaer** [comment]
As brought up [on the forum](https://discuss.write.as/t/writefreely-swiftui-multiplatform-app-mac-iphone-ipad/1664/7), the URL field can be confusing, especially for people who've never had to worry about an "instance URL" (e.g. Write.as users). So in addition to fixing the bug, I'd suggest we parse the URL in this field and automatically transform it to only include the `scheme` + `host`. E.g. `write.as/matt` should become `https://write.as`.

**Comment by AngeloStavrow** [comment]
> So in addition to fixing the bug, I'd suggest we parse the URL in this field and automatically transform it to only include the `scheme` + `host`. E.g. `write.as/matt` should become `https://write.as`.

Just adding a comment here: since WriteFreely instances _have_ to live at the root of a domain, we ~~can~~ ~~should be able to~~ probably won't get bitten by just removing the path that a user enters as part of the server URL.
