### ISSUE TITLE
Send user to login form when attempting to publish while logged out

### ISSUE THREAD

**Issue by thebaer** [writeas/writefreely-swiftui-multiplatform#82]
While a user is logged out of the app:

* The Publish button should remain enabled (as if they're logged in)
* When clicked, it should open the Settings screen so the user can log in
  * _Note:_ The screen should display a small descriptive message above the log in form, so users understand why they're there
* After successfully logging in, the user should be able to manually close the Settings screen and press the Publish button again -- this time, actually publishing the post.

**Comment by AngeloStavrow** [comment]
Reopening this for the macOS fix as well.
